[package]
name = "cesium_3d_tiles_generator"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
las = "0.7.5"
serde  = { version = "1", features = ["derive"] }
serde_json = "1"
